execute:
  execute_notebooks: binder
  timeout: 1200
  allow_errors: True
  exclude_patterns:
    - "notebooks/NISAR_GCOV*"

sphinx:
  config:
    html_theme: book-theme
    html_theme_options:
      launch_buttons:
        binderhub_url: "https://mybinder.org"
