name: 
channels:
  - conda-forge
dependencies:
  - _python_abi3_support=1.0=hd8ed1ab_2
  - affine=2.4.0=pyhd8ed1ab_1
  - aiobotocore=2.25.0=pyhcf101f3_0
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.2=py313h2082a12_0
  - aioitertools=0.12.0=pyhd8ed1ab_1
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - anyio=4.11.0=pyhcf101f3_0
  - appnope=0.1.4=pyhd8ed1ab_1
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py313h6535dbc_2
  - arrow=1.4.0=pyhcf101f3_0
  - asciitree=0.3.3=py_2
  - asf_search=10.1.2=pyhd8ed1ab_0
  - asf_search-base=10.1.2=pyhd8ed1ab_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.5=pyh29332c3_0
  - attrs=25.4.0=pyh71513ae_0
  - aws-c-auth=0.9.1=h753d554_5
  - aws-c-cal=0.9.8=hca30140_0
  - aws-c-common=0.12.5=hc919400_0
  - aws-c-compression=0.3.1=h61d5560_7
  - aws-c-event-stream=0.5.6=hada8b3e_4
  - aws-c-http=0.10.7=h241dc44_1
  - aws-c-io=0.23.2=hcea795d_2
  - aws-c-mqtt=0.13.3=hf26a141_8
  - aws-c-s3=0.8.6=h1e3b5a0_7
  - aws-c-sdkutils=0.2.4=h61d5560_2
  - aws-checksums=0.2.7=h61d5560_3
  - aws-crt-cpp=0.35.0=h44e95eb_2
  - aws-sdk-cpp=1.11.606=hf3ce6b4_6
  - azure-core-cpp=1.16.1=h88fedcc_0
  - azure-identity-cpp=1.13.2=h853621b_1
  - azure-storage-blobs-cpp=12.15.0=h10d327b_1
  - azure-storage-common-cpp=12.11.0=h7e4aa5d_1
  - azure-storage-files-datalake-cpp=12.13.0=hb288d13_1
  - babel=2.17.0=pyhd8ed1ab_0
  - backoff=2.2.1=pyhd8ed1ab_1
  - beautifulsoup4=4.14.2=pyha770c72_0
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - blosc=1.21.6=h7dd00d9_1
  - bokeh=3.8.0=pyhd8ed1ab_0
  - botocore=1.40.49=pyhd8ed1ab_0
  - bounded-pool-executor=0.0.3=pyhd8ed1ab_0
  - brotli=1.2.0=hca488c2_0
  - brotli-bin=1.2.0=hce9b42c_0
  - brotli-python=1.2.0=py313h79bbab8_0
  - bzip2=1.0.8=hd037594_8
  - c-ares=1.34.5=h5505292_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cartopy=0.25.0=py313h7d16b84_1
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=2.0.0=py313h224173a_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - ciso8601=2.3.3=py313h5b5ffa7_1
  - click=8.3.0=pyh707e725_0
  - click-plugins=1.1.1.2=pyhd8ed1ab_0
  - cligj=0.7.2=pyhd8ed1ab_2
  - cloudpickle=3.1.2=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contextily=1.6.2=pyhd8ed1ab_1
  - contourpy=1.3.3=py313ha61f8ec_3
  - cpython=3.13.9=py313hd8ed1ab_101
  - cycler=0.12.1=pyhd8ed1ab_1
  - cytoolz=1.1.0=py313h6535dbc_1
  - dask=2025.11.0=pyhcf101f3_0
  - dask-core=2025.11.0=pyhcf101f3_0
  - dateparser=1.2.2=pyhd8ed1ab_0
  - debugpy=1.8.17=py313hc37fe24_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - deprecated=1.3.1=pyhd8ed1ab_0
  - distributed=2025.11.0=pyhcf101f3_0
  - earthaccess=0.14.0=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - fasteners=0.19=pyhd8ed1ab_1
  - fftw=3.3.10=nompi_h6637ab6_110
  - fonttools=4.60.1=py313h7d74516_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.14.1=hce30654_0
  - freexl=2.0.0=h3ab3353_2
  - frozenlist=1.7.0=py313hf28abc0_0
  - fsspec=2025.10.0=pyhd8ed1ab_0
  - gdal=3.10.3=py313h976e3e5_26
  - geographiclib=2.1=pyhd8ed1ab_0
  - geopy=2.4.1=pyhd8ed1ab_2
  - geos=3.14.1=h5afe852_0
  - geotiff=1.7.4=hf862be1_4
  - gflags=2.2.2=hf9b8971_1005
  - giflib=5.2.2=h93a5062_0
  - glog=0.7.1=heb240a5_0
  - gtest=1.16.0=ha393de7_0
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - h5py=3.13.0=nompi_py313hcdf59df_100
  - hdf5=1.14.3=nompi_ha698983_109
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=hfee45f7_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib-resources=6.5.2=pyhd8ed1ab_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - ipykernel=7.1.0=pyh5552912_0
  - ipympl=0.9.8=pyhcf101f3_0
  - ipython=9.7.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - ipywidgets=8.1.8=pyhd8ed1ab_0
  - isce3=0.24.4=py313h1234567_5_cpu
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jmespath=1.0.1=pyhd8ed1ab_1
  - joblib=1.5.2=pyhd8ed1ab_0
  - json-c=0.18=he4178ee_0
  - json5=0.12.1=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py313h8f79df9_2
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jsonschema-with-format-nongpl=4.25.1=he01879c_0
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.4.10=pyhd8ed1ab_0
  - jupyterlab-myst=2.4.2=pyhd8ed1ab_1
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.28.0=pyhcf101f3_0
  - jupyterlab_widgets=3.0.16=pyhcf101f3_1
  - kerchunk=0.2.7=pyhd8ed1ab_0
  - kiwisolver=1.4.9=py313h7add70c_2
  - krb5=1.21.3=h237132a_0
  - lark=1.3.1=pyhd8ed1ab_0
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=hd64df32_1
  - libabseil=20250512.1=cxx17_hd41c47c_0
  - libaec=1.1.4=h51d1e36_0
  - libarchive=3.8.2=gpl_h46575ef_100
  - libarrow=22.0.0=h4f7d3e6_3_cpu
  - libarrow-acero=22.0.0=hc317990_3_cpu
  - libarrow-compute=22.0.0=h75845d1_3_cpu
  - libarrow-dataset=22.0.0=hc317990_3_cpu
  - libarrow-substrait=22.0.0=h144af7f_3_cpu
  - libblas=3.9.0=38_h51639a9_openblas
  - libbrotlicommon=1.2.0=h87ba0bc_0
  - libbrotlidec=1.2.0=h95a88de_0
  - libbrotlienc=1.2.0=hb1b9735_0
  - libcblas=3.9.0=38_hb0561ab_openblas
  - libcrc32c=1.1.2=hbdafb3b_0
  - libcurl=8.17.0=hdece5d2_0
  - libcxx=21.1.5=hf598326_0
  - libdeflate=1.25=hc11a715_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libevent=2.1.12=h2757513_1
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.5.2=he5f378a_0
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgdal-core=3.10.3=h2be85fc_26
  - libgfortran=15.2.0=hfcf01ff_1
  - libgfortran5=15.2.0=h742603c_1
  - libgoogle-cloud=2.39.0=head0a95_0
  - libgoogle-cloud-storage=2.39.0=hfa3a374_0
  - libgrpc=1.73.1=h3063b79_1
  - libiconv=1.18=h23cfdf5_2
  - libjpeg-turbo=3.1.2=hc919400_0
  - libkml=1.3.0=hc33e383_1022
  - liblapack=3.9.0=38_hd9741b5_openblas
  - liblzma=5.8.1=h39f12f2_2
  - libmpdec=4.0.0=h5505292_0
  - libnghttp2=1.67.0=hc438710_0
  - libopenblas=0.3.30=openmp_ha158390_3
  - libopentelemetry-cpp=1.21.0=he15edb5_1
  - libopentelemetry-cpp-headers=1.21.0=hce30654_1
  - libparquet=22.0.0=h0ac143b_3_cpu
  - libpng=1.6.50=h280e0eb_1
  - libprotobuf=6.31.1=h658db43_2
  - libre2-11=2025.11.05=h91c62da_0
  - librttopo=1.1.0=ha909e78_20
  - libsodium=1.0.20=h99b78c6_0
  - libspatialite=5.1.0=gpl_ha239c29_119
  - libsqlite=3.51.0=h8adb53f_0
  - libssh2=1.11.1=h1590b86_0
  - libthrift=0.22.0=h14a376c_1
  - libtiff=4.7.1=h4030677_1
  - libutf8proc=2.11.0=hc25f550_0
  - libuv=1.51.0=h6caf38d_1
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.15.1=h9329255_0
  - libxml2-16=2.15.1=h0ff4647_0
  - libxml2-devel=2.15.1=h9329255_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=21.1.5=h4a912ad_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.4.5=py313hd065f0a_0
  - lz4-c=1.10.0=h286801f_1
  - lzo=2.10=h925e9cb_1002
  - markupsafe=3.0.3=py313h7d74516_0
  - matplotlib-base=3.10.7=py313h58042b9_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mercantile=1.2.1=pyhd8ed1ab_1
  - minizip=4.0.10=hff1a8ea_0
  - mistune=3.1.4=pyhcf101f3_0
  - msgpack-python=1.1.2=py313ha61f8ec_1
  - multidict=6.6.3=py313h6347b5a_0
  - multimethod=2.0.1=pyhd8ed1ab_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - mystmd=1.6.4=pyhcf101f3_0
  - narwhals=2.10.2=pyhcf101f3_0
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyhcf101f3_1
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h5e97a16_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nlohmann_json=3.12.0=h248ca61_1
  - nodejs=24.4.1=hab9d20b_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numcodecs=0.15.1=py313h668b085_0
  - numpy=2.3.4=py313h9771d21_0
  - openjpeg=2.5.4=hbfb3c88_0
  - openssl=3.5.4=h5503f6c_0
  - orc=2.2.1=h4fd0076_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py313h7d16b84_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.5=pyhcf101f3_0
  - partd=1.4.2=pyhd8ed1ab_0
  - pathlib-abc=0.5.2=pyh9692d8f_0
  - pcre2=10.46=h7125dd6_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pillow=12.0.0=py313h54da0cd_0
  - pip=25.2=pyh145f28c_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - pqdm=0.2.0=pyhd8ed1ab_1
  - proj=9.7.0=hf83150c_0
  - prometheus-cpp=1.3.0=h0967b3e_0
  - prometheus_client=0.23.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - propcache=0.3.1=py313ha9b7d5b_0
  - psutil=7.1.3=py313h9734d34_0
  - pthread-stubs=0.4=hd74edd7_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyarrow=22.0.0=py313h39782a4_0
  - pyarrow-core=22.0.0=py313hb9a0e51_0_cpu
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyobjc-core=12.0=py313h40b429f_2
  - pyobjc-framework-cocoa=12.0=py313hcc5defa_2
  - pyparsing=3.2.5=pyhcf101f3_0
  - pyproj=3.7.2=py313h698103d_2
  - pyre=1.12.5=py313h72f4217_4
  - pyshp=3.0.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - pysolid=0.3.3=py313h657ee7e_4
  - python=3.13.9=hfc2f54d_101_cp313
  - python-cmr=0.13.0=pyhff2d567_1
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-gil=3.13.9=h4df99d1_101
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.13=8_cp313
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py313h7d74516_0
  - pyzmq=27.1.0=py312hd65ceae_0
  - qhull=2020.2=h420ef59_5
  - rasterio=1.4.3=py313hb3bd904_3
  - re2=2025.11.05=h64b956e_0
  - readline=8.2=h1d1bf99_2
  - referencing=0.37.0=pyhcf101f3_0
  - regex=2025.11.3=py313h6535dbc_1
  - remotezip=0.12.3=pyhd8ed1ab_1
  - requests=2.32.5=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rioxarray=0.20.0=pyhd8ed1ab_0
  - rpds-py=0.28.0=py313h2c089d5_1
  - ruamel.yaml=0.18.16=py313h6535dbc_0
  - ruamel.yaml.clib=0.2.14=py313h6535dbc_0
  - s3fs=2025.10.0=pyhd8ed1ab_0
  - scipy=1.16.3=py313h0d10b07_0
  - send2trash=1.8.3=pyh31c8845_1
  - setuptools=80.9.0=pyhff2d567_0
  - shapely=2.1.2=py313h10b2fc2_2
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=hd121638_0
  - sniffio=1.3.1=pyhd8ed1ab_1
  - snuggs=1.4.7=pyhd8ed1ab_2
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - soupsieve=2.8=pyhd8ed1ab_0
  - sqlite=3.51.0=h81ab1b7_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tblib=3.2.1=pyhcf101f3_0
  - tenacity=8.2.2=pyhd8ed1ab_0
  - terminado=0.18.1=pyh31c8845_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tinynetrc=1.3.1=pyhd8ed1ab_0
  - tk=8.6.13=h892fb3f_2
  - tomli=2.3.0=pyhcf101f3_0
  - toolz=1.1.0=pyhd8ed1ab_1
  - tornado=6.5.2=py313h6535dbc_2
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025b=h78e105d_0
  - tzlocal=5.3.1=pyh8f84b5b_0
  - ujson=5.11.0=py313hab38a8b_1
  - universal_pathlib=0.3.4=pyhd8ed1ab_0
  - uri-template=1.3.0=pyhd8ed1ab_1
  - uriparser=0.9.8=h00cdb27_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - virtualizarr=1.2.0=pyhd8ed1ab_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - webcolors=25.10.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.9.0=pyhd8ed1ab_0
  - widgetsnbextension=4.0.15=pyhd8ed1ab_0
  - wrapt=1.17.3=py313hcdf3177_1
  - xarray=2025.10.1=pyhd8ed1ab_0
  - xerces-c=3.3.0=hd62221f_0
  - xorg-libxau=1.0.12=h5505292_0
  - xorg-libxdmcp=1.1.5=hd74edd7_0
  - xyzservices=2025.10.0=pyhd8ed1ab_0
  - yamale=5.3.0=pyhd8ed1ab_0
  - yaml=0.2.5=h925e9cb_3
  - yarl=1.22.0=py313h7d74516_0
  - zarr=2.18.7=pyhd8ed1ab_0
  - zeromq=4.3.5=h888dc83_9
  - zict=3.0.0=pyhd8ed1ab_1
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h8359307_2
  - zlib-ng=2.2.5=h3470cca_0
  - zstandard=0.25.0=py313h9734d34_1
  - zstd=1.5.7=h6491c7d_2
  